bib_all: "TestLibrary.bib"
path_to_memex: ./_data/
path_to_index: ./_data/index.html
path_to_content: ./_data/contents.html
bibtex_keys: ./zotero_biblatex_keys.yml
language_keys: ./bibtex_languages.yml
ocr_results: .json
stopwords: ./_misc/stopwords/

template_page: ./_misc/template_page.html
template_index: ./_misc/template_index.html
content_index: ./_misc/content_index.html
template_search: ./_misc/template_search.html

memexDF_file: ./_data/memex.documentFrequencies
tfPubl_ext: .publTF 
tfPage_ext: .pageTF 
tfIdfPubl_ext: .publTFIDF
tfIdfPage_ext: .pageTFIDF
path_to_tfidf: /home/lisnux/Desktop/UniWien/WS2021/070172_UEMethodologicalCourse/hw070172/MEMEX_building/memex_sandbox/results_tfidf

# FILE NAMES WITH ANALYTICAL RESULTS
tfidf_publ: results_tfidf_publications.dataJson
publ_cosDist: results_cosineDist_publications.dataJson
page_cosDist: results_cosineDist_pages.dataJson
